/******** ABOUT FETCH ACTIONS ********/
export const LOAD_ABOUT_SUCCESS = 'LOAD_ABOUT_SUCCESS';
export const LOAD_ABOUT_FAILURE = 'LOAD_ABOUT_FAILURE';
export const ABOUT_FETCH_REQUESTED = 'ABOUT_FETCH_REQUESTED';

/******** INIT SESSION ********/
export const INIT_SESSION_REQUEST = 'INIT_SESSION_REQUEST';
export const INIT_SESSION_SUCCESS = 'INIT_SESSION_SUCCESS';
export const INIT_SESSION_FAILURE = 'INIT_SESSION_FAILURE';

/******** FETCHING CONTROL ACTIONS ********/
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_RECEIVE = 'FETCH_RECEIVE';

/******** MAIN IMAGES ********/
export const GET_MAIN_IMAGES = 'GET_MAIN_IMAGES';
export const GET_MAIN_IMAGES_SUCCESS = 'GET_MAIN_IMAGES_SUCCESS';
export const GET_MAIN_IMAGES_FAILURE = 'GET_MAIN_IMAGES_FAILURE';

/******** AUTH ACTIONS ********/
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_ERROR_CREDENTIALS = 'LOGIN_ERROR_CREDENTIALS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_SEND_FAILED = 'PASSWORD_SEND_FAILED';
export const PASSWORD_SEND_ERROR = 'PASSWORD_SEND_ERROR';

/******** MODAL ACTIONS ********/
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const MODAL_TYPE_REGISTER = 'MODAL_TYPE_REGISTER';
export const MODAL_TYPE_LOGIN = 'MODAL_TYPE_LOGIN';
export const MODAL_TYPE_PASSWORD_RESET = 'MODAL_TYPE_PASSWORD_RESET';
export const MODAL_TYPE_SUCCESS = 'MODAL_TYPE_SUCCESS';
export const MODAL_TYPE_LOADING = 'MODAL_TYPE_LOADING';
export const MODAL_TYPE_ADD_BUILDING_OBJECT = 'MODAL_TYPE_ADD_BUILDING_OBJECT';
export const MODAL_TYPE_CONFIRM_ORDER_SUCCESS = 'MODAL_TYPE_CONFIRM_ORDER_SUCCESS';

/******** SEARCH ********/
export const SEARCH_PRODUCTS_REQUEST = 'SEARCH_PRODUCTS_REQUEST';
export const SEARCH_PRODUCTS_SUCCESS = 'SEARCH_PRODUCTS_SUCCESS';
export const SEARCH_PRODUCTS_FAILURE = 'SEARCH_PRODUCTS_FAILURE';
export const SEARCH_PRODUCTS_ERROR = 'SEARCH_PRODUCTS_ERROR';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

/******** CATEGORIES ********/
export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';

/******** PRODUCT LIST ********/
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const CLEAR_GET_PRODUCTS_RESULT = 'CLEAR_GET_PRODUCTS_RESULT';
export const All_PRODUCTS_CHECK = 'ALL_PRODUCTS_CHECK';
export const All_PRODUCTS_CHECK_CLEAR = 'ALL_PRODUCTS_CHECK_CLEAR';

/******** PRODUCT ********/
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
export const CLEAR_GET_PRODUCT_RESULT = 'CLEAR_GET_PRODUCT_RESULT';
export const ADD_CURRENT_PRODUCT = 'ADD_CURRENT_PRODUCT';

/******** BUILDING ********/
export const CREATE_BUILDING_OBJECT_REQUEST = 'CREATE_BUILDING_OBJECT_REQUEST';
export const CREATE_BUILDING_OBJECT_SUCCESS = 'CREATE_BUILDING_OBJECT_SUCCESS';
export const CREATE_BUILDING_OBJECT_FAILURE = 'CREATE_BUILDING_OBJECT_FAILURE';

export const LIST_BUILDING_OBJECTS_REQUEST = 'LIST_BUILDING_OBJECTS_REQUEST';
export const LIST_BUILDING_OBJECTS_SUCCESS = 'LIST_BUILDING_OBJECTS_SUCCESS';
export const LIST_BUILDING_OBJECTS_FAILURE = 'LIST_BUILDING_OBJECTS_FAILURE';

export const SET_CURRENT_BUILDING_OBJECT = 'SET_CURRENT_BUILDING_OBJECT';
export const CLEAR_CURRENT_BUILDING_OBJECT = 'CLEAR_CURRENT_BUILDING_OBJECT';

export const CLEAR_BUILDING_OBJECTS = 'CLEAR_BUILDING_OBJECTS';

export const DELETE_MATERIAL_REQUEST = 'DELETE_MATERIAL_REQUEST';
export const DELETE_MATERIAL_SUCCESS = 'DELETE_MATERIAL_SUCCESS';
export const DELETE_MATERIAL_FAILURE = 'DELETE_MATERIAL_FAILURE';

export const UPDATE_MATERIAL_AMOUNT_REQUEST = 'UPDATE_MATERIAL_AMOUNT_REQUEST';
export const UPDATE_MATERIAL_AMOUNT_SUCCESS = 'UPDATE_MATERIAL_AMOUNT_SUCCESS';
export const UPDATE_MATERIAL_AMOUNT_FAILURE = 'UPDATE_MATERIAL_AMOUNT_FAILURE';

/******** CART ********/
export const GET_CART_LIST_REQUEST = 'GET_CART_LIST_REQUEST';
export const GET_CART_LIST_SUCCESS = 'GET_CART_LIST_SUCCESS';
export const GET_CART_LIST_FAILURE = 'GET_CART_LIST_FAILURE';

export const ADD_TO_CART_LIST_REQUEST = 'ADD_TO_CART_LIST_REQUEST';
export const ADD_TO_CART_LIST_SUCCESS = 'ADD_TO_CART_LIST_SUCCESS';
export const ADD_TO_CART_LIST_FAILURE = 'ADD_TO_CART_LIST_FAILURE';

export const REMOVE_FROM_CART_LIST_REQUEST = 'REMOVE_FROM_CART_LIST_REQUEST';
export const REMOVE_FROM_CART_LIST_SUCCESS = 'REMOVE_FROM_CART_LIST_SUCCESS';
export const REMOVE_FROM_CART_LIST_FAILURE = 'REMOVE_FROM_CART_LIST_FAILURE';

export const CHANGE_CART_INFO = 'CHANGE_CART_INFO';

export const CLEAR_CART = 'CLEAR_CART';

/******** CHECKOUT ********/
export const ADD_INFO_TO_CHECKOUT_OBJECT = 'ADD_INFO_TO_CHECKOUT_OBJECT';
export const ADD_BUILDING_OBJECT = 'ADD_BUILDING_OBJECT';
export const DELETE_BUILDING_OBJECT = 'DELETE_BUILDING_OBJECT';
export const CLEAR_BUILDING_OBJECTS_CHECKOUT = 'CLEAR_BUILDING_OBJECTS_CHECKOUT';
export const ADD_SHIPPING_ADDRESS = 'ADD_SHIPPING_ADDRESS';
export const ADD_CARD_INFO = 'ADD_CARD_INFO';
export const CONFIRM_ORDER_REQUEST = 'CONFIRM_ORDER_REQUEST';
export const CONFIRM_ORDER_SUCCESS = 'CONFIRM_ORDER_SUCCESS';
export const CONFIRM_ORDER_FAILURE = 'CONFIRM_ORDER_FAILURE';

export const GET_STRIPE_TOKEN_REQUEST = 'GET_STRIPE_TOKEN_REQUEST';
export const GET_STRIPE_TOKEN_SUCCESS = 'GET_STRIPE_TOKEN_SUCCESS';
export const GET_STRIPE_TOKEN_FAILURE = 'GET_STRIPE_TOKEN_FAILURE';

export const CONFIRM_ORDER_MODAL_CLOSE = 'CONFIRM_ORDER_MODAL_CLOSE';

export const CLEAR_CHECKOUT = 'CLEAR_CHECKOUT';

/******** PROFILE ********/
export const GET_PROFILE_DATA_REQUEST = 'GET_PROFILE_DATA_REQUEST';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_FAILURE = 'GET_PROFILE_DATA_FAILURE';

export const UPDATE_PROFILE_DATA_REQUEST = 'UPDATE_PROFILE_DATA_REQUEST';
export const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS';
export const UPDATE_PROFILE_DATA_FAILURE = 'UPDATE_PROFILE_DATA_FAILURE';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';

/******** INVOICES ********/
export const LIST_INVOICES_REQUEST = 'LIST_INVOICES_REQUEST';
export const LIST_INVOICES_SUCCESS = 'LIST_INVOICES_SUCCESS';
export const LIST_INVOICES_FAILURE = 'LIST_INVOICES_FAILURE';

export const SET_PAGE_SIZE_INVOICES = 'SET_PAGE_SIZE_INVOICES';
export const SET_SEARCH_QUERY_INVOICES = 'SET_SEARCH_QUERY_INVOICES';

export const CLEAR_INVOICES = 'CLEAR_INVOICES';

/******** WISH LIST ********/
export const ADD_TO_WISH_LIST_REQUEST = 'ADD_TO_WISH_LIST_REQUEST';
export const ADD_TO_WISH_LIST_SUCCESS = 'ADD_TO_WISH_LIST_SUCCESS';
export const ADD_TO_WISH_LIST_FAILURE = 'ADD_TO_WISH_LIST_FAILURE';

export const REMOVE_FROM_WISH_LIST_REQUEST = 'REMOVE_FROM_WISH_LIST_REQUEST';
export const REMOVE_FROM_WISH_LIST_SUCCESS = 'REMOVE_FROM_WISH_LIST_SUCCESS';
export const REMOVE_FROM_WISH_LIST_FAILURE = 'REMOVE_FROM_WISH_LIST_FAILURE';

export const GET_WISH_LIST_REQUEST = 'GET_WISH_LIST_REQUEST';
export const GET_WISH_LIST_SUCCESS = 'GET_WISH_LIST_SUCCESS';
export const GET_WISH_LIST_FAILURE = 'GET_WISH_LIST_FAILURE';

export const CLEAR_WISH_LIST = 'CLEAR_WISH_LIST';

/******** ARTICLE LIST ********/
export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';

/******** ARTICLE ********/
export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

/******** CURRENCY ********/
export const GET_CURRENCY_REQUEST = 'GET_CURRENCY_REQUEST';
export const GET_CURRENCY_SUCCESS = 'GET_CURRENCY_SUCCESS';
export const GET_CURRENCY_FAILURE = 'GET_CURRENCY_FAILURE';

/******** PAGINATION ********/
export const SET_START_PAGINATION = 'SET_START_PAGINATION';
export const CLEAR_START_PAGINATION = 'CLEAR_START_PAGINATION';