/******** FETCHING CONTROL ACTIONS ********/
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_RECEIVE = 'FETCH_RECEIVE';




export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const LOGOUT = "USERS_LOGOUT";


export const ADD_GROUP = "ADD_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
