/******** ABOUT FETCH ACTIONS ********/
export const LOAD_ABOUT_SUCCESS = 'LOAD_ABOUT_SUCCESS';
export const LOAD_ABOUT_FAILURE = 'LOAD_ABOUT_FAILURE';
export const ABOUT_FETCH_REQUESTED = 'ABOUT_FETCH_REQUESTED';

/******** INIT SESSION ********/
export const INIT_SESSION_REQUEST = 'INIT_SESSION_REQUEST';
export const INIT_SESSION_SUCCESS = 'INIT_SESSION_SUCCESS';
export const INIT_SESSION_FAILURE = 'INIT_SESSION_FAILURE';

/******** FETCHING CONTROL ACTIONS ********/
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_RECEIVE = 'FETCH_RECEIVE';


/******** AUTH ACTIONS ********/
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_CANCELLED = 'LOGIN_CANCELLED';

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_ERROR_CREDENTIALS = 'LOGIN_ERROR_CREDENTIALS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';


/******** MODAL ACTIONS ********/
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const MODAL_TYPE_REGISTER = 'MODAL_TYPE_REGISTER';
export const MODAL_TYPE_LOGIN = 'MODAL_TYPE_LOGIN';
export const MODAL_TYPE_PASSWORD_RESET = 'MODAL_TYPE_PASSWORD_RESET';
export const MODAL_TYPE_SUCCESS = 'MODAL_TYPE_SUCCESS';
export const MODAL_TYPE_LOADING = 'MODAL_TYPE_LOADING';
export const MODAL_TYPE_ADD_BUILDING_OBJECT = 'MODAL_TYPE_ADD_BUILDING_OBJECT';
export const MODAL_TYPE_CONFIRM_ORDER_SUCCESS = 'MODAL_TYPE_CONFIRM_ORDER_SUCCESS';



export const ADD_ARTICLE = "ADD_ARTICLE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
